site_name: 'AI Docs'
site_description: 'ML Knowledge Documentation'
site_author: 'J Sundar'

repo_url: https://github.com/ai-docs/knowledge

theme:
  name: null
  custom_dir: nav_pages
  # Copy settings from mkdocs_theme.yml, which is ignored by custom_dir themes.
  static_templates: [404.html]
  search_index_only: true
  include_search_page: true

pages:
- Samples:
  - Sample Page A: sample-a.md
  - Sample Subfolder:
    - Sample Subpage A1: sample-a1.md
    - Sample Subpage A2: sample-a2.md
  - Sample Page B: sample-b.md

markdown_extensions:
  - toc:
      permalink: 

extra:
  history_buttons: false
  version: 0.1.1